### ISSUE TITLE
[rubysrc] tracking bug for simpler misc issues

### ISSUE THREAD

**Issue by maltek** [joernio/joern#4822]
I'll use this issue as a tracker bug for simpler issues. I might add more things as I come across them.

- [ ] identifiers for `self` parameters are missing REF edges to the corresponding parameters
- [ ] other identifiers are created without any matching local nodes (just run `cpg.identifier.not(_.refsTo).size` e.g. on railsgoat)
- [ ] the argument `0` of `<operator>.alloc` calls seems to always created get as an identifier, even if it's a complex expression (e.g. https://github.com/OWASP/railsgoat/blob/c1e8ff1e3b24a1c48fcfc9fbee0f65dc296b49d9/app/controllers/api/v1/mobile_controller.rb#L10)
- [ ] when a class is defined within a namespace, e.g. `class Api::V1::MobileController`, the type decl has a name field `Api`. The actual name `MobileController` is nowhere in the CPG, not even in the type's full name.
- [ ] parsing an empty file runs into a null pointer exception
- [ ] the detection of builtin method calls is a bit too eager, e.g. https://github.com/OWASP/railsgoat/blob/master/app/models/analytics.rb#L3 is translated as a call to `__core.Kernel.select` which it isn't
- [ ] the way that splitting receiver/arg 0 of calls was implemented, leads to a huge amount of duplication for chained method calls: `a().b().c().d()` has 1 call with name `a`, 2 calls with name `b`, 3x `c` and 4x `d`. Compare with e.g. jssrc: there, the receiver is an assignment `(_tmp_1 = a().b()).c` and argument 0 is simply a reference to that identifier `_tmp_1`

**Comment by AndreiDreyer** [comment]
@maltek I'm struggling to recreate the issue for `detection of builtin method calls are a bit too eager`. If I use the snippet you linked in a test case in the Ruby frontend and run: 
```scala
    cpg.call.name("select").l.foreach(x => println(s"${x.code}: ${x.typeFullName} ${x.dynamicTypeHintFullName} ${x.possibleTypes}"))
```
then none of the calls to `select` has any types
![image](https://github.com/user-attachments/assets/dda3ef2b-7015-4dac-a0e0-2063b56b4bd9)

**Comment by AndreiDreyer** [comment]
The line of the code snippet provided for the `<operator>.alloc` call issue doesn't have any calls to `<operator>.alloc`.
![image](https://github.com/user-attachments/assets/58a74f36-159a-4204-9b5e-64ebcc63ceaa)

**Comment by maltek** [comment]
@AndreiDreyer for the `select` call, it's the `methodFullName` that is set to "__core.Kernel.select" (and thereby also the `CALL` edge)

I don't know why you don't see that `<operator>.alloc` call - I get 44 alloc calls when importing that commit of railsgoat. (Both with latest joern and qwiet's current ruby2cpg-internal.)

**Comment by AndreiDreyer** [comment]
Thanks, I got the `select` one working. This is a tough one to fix, I'll have to discuss it with David when he is back. I considered moving it into the `possibleTypes` and then possibly populating the fullName at a later stage possibly with an independent pass, but it seems the only type that is in the `possibleTypes` is the `__core.Kernel.select` so this would end up having the same issue. I will start looking at some of the other bugs in the mean time

**Comment by DavidBakerEffendi** [comment]
For `other identifiers are created without any matching local nodes (just run cpg.identifier.not(_.refsTo).size e.g. on railsgoat)`, it will be a multi-issue solution, as there seems to be two or three identifiable reasons for this. 
* Implicit require calls follow an old/incorrect representation that creates `require` identifier bases
* Type references or constants that are imported from elsewhere don't have a local (Should this be a type ref? Should I create a local? cc @ml86)
* Some other misc ones about member accesses from an index access

**Comment by maltek** [comment]
@DavidBakerEffendi sorry, fixed the linked line now. (`cpg.call.name(Operators.alloc).codeExact("params[:type].constantize.new(path)").receiver.l` gives an identifier for the expression `params[:type].constantize`)

**Comment by DavidBakerEffendi** [comment]
Wrt `.erb` files, depending on immediate desire, there are some off-the-shelf solutions: 
https://github.com/jarrett/erb_parser
https://stackoverflow.com/questions/2588967/library-to-parse-erb-files
However, they may not have any guarantees on handling complex Ruby code in `.erb` files, rather "common" syntax in `.erb` files. Either way, we have our own Ruby parser to give these Ruby fragments to once we've separated them from the template.

**Comment by AndreiDreyer** [comment]
@maltek for the issue `classes defined within a namespace are missing the AST edges to their parent namespace block`, is this for a class defined as follows:
```ruby
class Foo
  class Bar
  end
end
```
where `Bar` should have an edge to `Foo`, or is it for a class defined as:
```ruby
class Foo::Bar
end
```

**Comment by maltek** [comment]
@AndreiDreyer I've observed it with the `Foo::Bar` syntax. I haven't verified that the other case is fine, though.

**Comment by AndreiDreyer** [comment]
@maltek do you perhaps have the query that you ran so I can replicate the issue?

**Comment by maltek** [comment]
@AndreiDreyer sorry, it seems that was on an outdated branch or something. I can't reproduce the missing AST edges anymore. There's still something wrong with https://github.com/OWASP/railsgoat/blob/c1e8ff1e3b24a1c48fcfc9fbee0f65dc296b49d9/app/controllers/api/v1/mobile_controller.rb though: `cpg.namespaceBlock.fullNameExact("Api.V1").typeDecl` returns typedecls (among others) `....rb:<main>.Api.V1.MobileController` and `.rb:<main>.MobileController<class>`. First, that's inconsistent. But more importantly, querying for the `.method`s of those type decls returns nothing. The methods exist in the CPG, but for a third typedecl `....rb:<main>.MobileController` that seems to be only created as a type stub.

**Comment by AndreiDreyer** [comment]
@maltek could you re-test the `classes defined within namespace are not linked to their methods`? It might have been fixed when I fixed the namespace inconsistencies.
